model:
  input_shape: [192, 224, 176, 1]
  base_filters: 16  # Reduced from 32
  depth: 4          # Reduced from 5
  use_attention: true
  use_deep_supervision: false  # Disabled to save memory

training:
  epochs: 100
  batch_size_per_gpu: 1  # Reduced from 2
  learning_rate: 0.0001
  validation_split: 0.2
  patience: 15
  global_batch_size: 1

data:
  data_dir: '/mnt/beegfs/hellgate/home/rb194958e/Atlas_2/Training'
  cache_dir: '/tmp/stroke_cache'
  num_workers: 4
  prefetch: 2
